version: '3'
services:
  node-backend-api:
    container_name: node-backend-api
    build: ./node-backend-api
    ports:
      - "3000:3000"
    depends_on:
      - redis-service
      - kafka
    env_file:
      - ./node-backend-api/.env.production

  redis-service:
    container_name: redis-service
    image: "redis:alpine"
    environment:
      - REDIS_PASSWORD=your_password
    command:
      - redis-server
      - "--requirepass"
      - "your_password"
      - "--maxmemory"
      - "100mb"
      - "--maxmemory-policy"
      - "allkeys-lru"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data

  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:latest
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cmak:
    container_name: cmak
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    volumes:
      - ./data/cmak:/cmak-data