apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmak-pvc
  labels:
    app: cmak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmak
  labels:
    app: cmak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmak
  template:
    metadata:
      labels:
        app: cmak
    spec:
      containers:
      - name: cmak
        image: hlebalbau/kafka-manager:latest
        ports:
          - containerPort: 9000
        env:
          - name: ZK_HOSTS
            value: "zookeeper-service:2181"  # Update if your ZK service name differs
        volumeMounts:
          - name: cmak-data
            mountPath: /cmak-data
      volumes:
        - name: cmak-data
          persistentVolumeClaim:
            claimName: cmak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cmak-service
  labels:
    app: cmak
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: cmak
