apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-consumer
  template:
    metadata:
      labels:
        app: flink-consumer
    spec:
      containers:
      - name: flink-consumer
        image: flink-consumer:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:29092"
        - name: KAFKA_GROUP_ID
          value: "flink-group"
        - name: KAFKA_TOPIC
          value: "mock-user-topic"
        - name: DB_URL
          value: "jdbc:oracle:thin:@oracle-db-service:1521/jorgermduarte"
        - name: DB_USERNAME
          value: "jorgermduarte"
        - name: DB_PASSWORD
          value: "123456"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: flink-consumer-service
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 31081
  selector:
    app: flink-consumer
