apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-consumer
  template:
    metadata:
      labels:
        app: flink-consumer
    spec:
      containers:
      - name: flink-consumer
        image: flink-consumer:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: flink-consumer-env
---
apiVersion: v1
kind: Service
metadata:
  name: flink-consumer-service
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 31081
  selector:
    app: flink-consumer
