apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
      - name: ocelot-api-gateway
        image: gateway-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://*:80"

---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
  selector:
    app: ocelot-api-gateway
