apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend-api
  template:
    metadata:
      labels:
        app: node-backend-api
    spec:
      containers:
      - name: node-backend-api
        image: node-backend-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis-service"  # Nome DNS do serviço Redis no Kubernetes
        - name: REDIS_PORT
          value: "6379"  # Porta do Redis
        - name: REDIS_PASSWORD
          value: "your_password"  # Senha do Redis
        - name: KAFKA_BROKER
          value: "kafka-service:9092"  # Nome DNS do serviço Kafka no Kubernetes
        # envFrom:
        # - configMapRef:
        #     name: node-backend-api-env
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-api-service
spec:
  type: NodePort
  ports:
  - port: 3001
    nodePort: 30001
  selector:
    app: node-backend-api
