apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-db
        image: gvenzl/oracle-xe
        env:
        - name: APP_USER
          value: "jorgermduarte"
        - name: APP_USER_PASSWORD
          value: "123456"
        - name: ORACLE_DATABASE
          value: "jorgermduarte"
        - name: ORACLE_PASSWORD
          value: "123456"
        ports:
        - containerPort: 1521
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: oracle-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1521
          initialDelaySeconds: 120
          periodSeconds: 30
      volumes:
      - name: oracle-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db-service
  labels:
    app: oracle-db
spec:
  type: NodePort
  ports:
  - port: 1521
    targetPort: 1521
    nodePort: 31521
    protocol: TCP
    name: oracle-db
  - port: 8080
    targetPort: 8080
    nodePort: 30800
    protocol: TCP
    name: oracle-http
  selector:
    app: oracle-db
